# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Yu-Gi-Oh! Card Database

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  spider-job:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yugioh-scraper
    - name: Run Spider
      run: db_yugiohcard
    - name: Uploads Data Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: db-yugioh-card
        path: jobs/db_yugioghcard
        retention-days: 30
  
  upload-data:
    needs: [spider-job]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v3
      - name: Downloads all workflow artifacts
        uses: actions/download-artifact@v3
        with:
          name: db-yugioh-card
          path: raw/yugioh_card_db
      - name: Push to Code Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "`date +"%Y-%m-%d:%H:%M:%S"` db-yugioh-card"
          git push


